[BE] Directory 구조 변경 / Mongoose 추가 / Swagger 설치
boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-Server pull request #16
Opened 2020-11-23 11:37 UTC by Kangsukmin

### Issue Number

### 변경사항

- 개발환경 변경
- mongoose 연동
- 폴더 구조 변경

### 새로운 기능

- SDK catchError 기능 샘플 추가
- Swagger 추가
- Log 설정

### 작업 유형
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 문서 업데이트

### 체크리스트
- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2020-11-23 13:52 UTC, gitdog01 approved these changes
확인했습니다 !

2020-11-23 14:13 UTC, maong0927 commented on package.json
> +    "prettier": "^2.1.",
왜 2.1. 밖에없죵!! ?

2020-11-23 14:37 UTC, Kangsukmin commented on package.json
> +    "prettier": "^2.1.",
?!

2020-11-23 14:55 UTC, maong0927 requested changes

2020-11-23 14:55 UTC, maong0927 commented on package.json
> -    "ts-node": "^9.0.0"
ts-node 를 깔아주세용!!

2020-11-24 01:27 UTC, Eunbin-Kim requested changes

2020-11-24 01:27 UTC, Eunbin-Kim commented on package.json
> +>>>>>>> feature/setting
이 부분 코드 conflict 났던 부분인 것 같은데 지워주세용!

2020-11-24 01:27 UTC, Eunbin-Kim commented on src/config/server.ts
> +process.env.PORT = process.env.PORT || '3000';
process.env 에 직접 override 하는 것 보다 const 변수 선언해서 담는게 더 좋지 않을까 생각되는데 어떻게 생각하시나요..!
const PORT = process.env.PORT || 3000;

2020-11-24 01:29 UTC, Eunbin-Kim requested changes

2020-11-24 01:29 UTC, Eunbin-Kim commented on src/config/mongoDB.ts
> +process.env.MONGODB_URI = process.env.MONGODB_URI || '';
여기도 변수안에 담는 방법으로 고려 부탁드려요!

2020-11-24 01:33 UTC, maong0927 approved these changes
👍

2020-11-24 03:03 UTC, Eunbin-Kim approved these changes
확인했습니다~!

2020-11-24 04:25 UTC, merged