[BE] Auth 기능 리팩토링, CheckEmail 기능 추가
boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-Server pull request #18
Opened 2020-11-26 08:03 UTC by Kangsukmin

### Issue Number
Close #

### 변경사항

- 의존성 목록

### 새로운 기능

- 기능 목록

### 작업 유형
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 문서 업데이트

### 체크리스트
- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [x] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2020-11-26 13:06 UTC, gitdog01 approved these changes
수고했어요 ~

2020-11-26 13:06 UTC, gitdog01 commented on src/api/route/admin/auth/controller.ts
> +    return res.status(200).end();
201 이였는데 200 으로 바꾼 이유가 뭔가요 ?

2020-11-26 17:09 UTC, maong0927 commented on src/api/route/admin/auth/controller.ts
> +    return res.status(200).end();
저도 궁금합니다 ㅠ 저의 201이 ..

2020-11-27 01:30 UTC, Eunbin-Kim requested changes

2020-11-27 01:30 UTC, Eunbin-Kim commented on .env.example
> +NODE_ENV= production | developer
다른 곳에서도 development로 사용하였으니 development로 맞추면 좋을 것 같습니다!

2020-11-27 01:44 UTC, Kangsukmin commented on .env.example
> +NODE_ENV= production | developer
넵 다음 PR때 수정하겠습니다. 로더나 다른파일쪽에 developer라 쓴곳이많네요

2020-11-27 01:46 UTC, Kangsukmin commented on src/api/route/admin/auth/controller.ts
> +    return res.status(200).end();
찾아보니 201이 맞는거 같네요. 아마 Swagger에 200으로 통일해서 하려했던거 같은데 수정하겠습니다.

2020-11-27 01:46 UTC, Kangsukmin commented on src/api/route/admin/auth/controller.ts
> +    return res.status(200).end();
이외 Create 관련 메소드는 다 201로 하겠습니다.

2020-11-27 01:51 UTC, Eunbin-Kim approved these changes
고생많으셨어용!

2020-11-27 01:51 UTC, maong0927 approved these changes

2020-11-27 01:58 UTC, merged