[BE] Swagger 설정 / 기타 코드 수정
boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-Server pull request #20
Opened 2020-11-26 10:53 UTC by Kangsukmin

### Issue Number
Close #

### 변경사항

- 코드 오타 수정

### 새로운 기능

- Swagger 코드 추가

### 작업 유형
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 문서 업데이트

### 체크리스트
- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2020-11-26 13:16 UTC, gitdog01 approved these changes
swagger 넣은거 잘 봤어요 ~

2020-11-26 17:04 UTC, maong0927 requested changes

2020-11-26 17:04 UTC, maong0927 commented on src/api/route/admin/project/controller.ts
> +    const { user } = req;
여기 하나로 만들 수 있을거같아요 윗줄이랑 !!

2020-11-26 17:04 UTC, maong0927 commented on src/api/route/admin/project/controller.ts
> +    const { user } = req;
여기 36-40줄까지 let을 안써도 될거같습니다!! 그리고 한꺼번에 받아올 수 있을거같아용!!

2020-11-26 17:05 UTC, maong0927 commented
위 pr 이랑 같은 코드가 많이 보이는데 혹시 위 pr이 수정된 버전인가용?

2020-11-27 01:46 UTC, Eunbin-Kim commented on src/api/route/admin/project/controller.ts
> +    const { pid } = req.params;
조금 길어지더라도 projectId라고 명시해주는 것이 좋다고 생각하는데 고려 부탁드립니당

2020-11-27 01:46 UTC, Eunbin-Kim approved these changes

2020-11-27 01:55 UTC, Kangsukmin commented on src/api/route/admin/project/controller.ts
> +    const { user } = req;
넵 한줄로 변경하겠습니다.

2020-11-27 02:08 UTC, maong0927 approved these changes

2020-11-27 02:10 UTC, merged