[BE] Issue API 추가, 미완성
boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-Server pull request #21
Opened 2020-11-26 10:57 UTC by Kangsukmin

### Issue Number
Close #

### 변경사항

- Pagenate 추가
- ajv 기능 추가

### 새로운 기능

- Issue 테스트
  - page에 number만 가능

### 작업 유형
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 문서 업데이트

### 체크리스트
- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2020-11-26 13:25 UTC, gitdog01 approved these changes

2020-11-26 13:25 UTC, gitdog01 commented on src/api/middlewares/sdkMiddleware.ts
> +  const project = await db.Project.findById(projectId);
매직 넘버 바꾸는거 어떨까요 ??

2020-11-26 16:59 UTC, maong0927 requested changes
:+1

2020-11-26 16:59 UTC, maong0927 commented on src/api/route/admin/issue/controller.ts
> +  let { page } = req.query;
req.query 를 다른 변수로 받은 다음에  그 타입에 따라서 새로운 변수( page )에 page 를 담는 건 어떨까요??
요런식으로용!!
```
const {query} = req;
const page = (typeof query.page !== 'string'? 1 : query.page);
```

2020-11-26 16:59 UTC, maong0927 commented on src/api/route/admin/project/controller.ts
> +    const { user } = req;
15줄이랑 16줄 하나로 만들 수 있지 않을까용?!

2020-11-26 16:59 UTC, maong0927 commented on src/api/route/admin/project/controller.ts
> +    const { user } = req;
여기도 한번에 받아올 수 있지 않을까용!?!

2020-11-26 16:59 UTC, maong0927 commented on src/config/swagger.ts
> +    version: process.env.npm_package_version as string, // Version (required)
오오 저번에 말하셨던 그거군여

2020-11-26 16:59 UTC, maong0927 commented on src/services/issue/getIssues.ts
> +  const result = await db.Issue.paginate({}, { page, limit: 10 });
여기 매직넘버 정리할 수 있지 않을까용??

2020-11-26 16:59 UTC, maong0927 commented on src/services/project/getProjects.ts
> +        limit: 10,
여기도용!!

2020-11-27 01:50 UTC, Eunbin-Kim approved these changes

2020-11-27 01:50 UTC, Eunbin-Kim reviewed
확인했습니다~!

2020-11-27 02:07 UTC, Kangsukmin commented on src/services/project/getProjects.ts
> +        limit: 10,
pagenation setting 변수를 하나 만들어서 { ...setting, page } 식으로 쓰면 좋을거 같네요

2020-11-27 02:10 UTC, maong0927 approved these changes

2020-11-27 02:11 UTC, merged